### ISSUE TITLE
`kleat generate` expects that the output dir already exists

### ISSUE THREAD

**Issue by achew22** [spinnaker/kleat#110]
If `kleat generate` is invoked with a dir an output dir that doesn't exist, you get the following error.

```
Error: stat ./generated: no such file or directory
```

Proposed solutions:

1. Notify the user that they need to create that directory
2. Make that directory for the user
3. Something else I didn't think of?

Which would you prefer in the PR?

**Comment by ezimanyi** [comment]
Thanks for opening this!  I'd say it's probably reasonable to go with (2).  I guess we'd still want to error with a sensible message in the event the directory can't be created (ex: because you gave it an existing regular file, or because we don't have permission to)...but if we're able to create it, it seems more user-friendly to do that rather than error and make the user create it.
